name: DFInhibition
version: '1.0-SNAPSHOT'
main: uk.co.nikodem.dFInhibition.DFInhibition
api-version: '1.20'
commands:
  startsmp:
    description: "Starts the SMP. Needs to be ran from the console."
    usage: "/startsmp"
  prepsmp:
    description: "Preps the world for SMP. Needs to be ran from the console."
    usage: "/prepsmp"
  milestones:
    description: "Shows you how long until a feature is enabled."
    usage: "/milestones"
  enablepvp:
    description: "Enables pvp. Needs to be ran from the console."
    usage: "/enablepvp"
  enablenether:
    description: "Enables the nether. Needs to be ran from the console."
    usage: "/enablenether"
  enableend:
    description: "Enables the end. Needs to be ran from the console."
    usage: "/enableend"