name: DFSmpPlugin
version: '1.0.2'
main: uk.co.nikodem.dFSmpPlugin.DFSmpPlugin
api-version: '1.20'
commands:
  lobby:
    description: "Teleports you back to the lobby if you are not in combat."
    aliases: ["hub"]
  bin:
    description: "Opens a gui where you can throw things away"
    aliases: ["rubbish", "trash", "garbage"]